entry=input("")
entry1=entry.lower()
entry1= entry1.replace("a","")
entry1= entry1.replace("e","")
entry1= entry1.replace("i","")
entry1= entry1.replace("o","")
entry1= entry1.replace("u","")
f=(".".join(entry1))
print("."+f)